---
hide_body: false
fields:
- name: date
  label: Date
  type: field_group
  hidden: false
  default: {}
- name: description
  label: Description
  type: text
  hidden: false
  default: ''
- name: categories
  label: Categories
  type: tag_list
  hidden: false
  default: []
- name: slug
  label: Slug
  type: text
  hidden: false
  default: ''
- name: aliases
  label: Aliases
  type: list
  hidden: false
  default: []
- name: toc
  label: Toc
  type: boolean
  hidden: false
  default: false
